name: Node.js CI

on:
  push:
    paths:
      - 't2-lifestyle-checker/**'
    branches:
      - main
  pull_request:
    paths:
      - 't2-lifestyle-checker/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        working-directory: ./t2-lifestyle-checker
        run: npm install
        
      - name: Run tests
        working-directory: ./t2-lifestyle-checker
        env:
            REACT_APP_API_SUBSCRIPTION_KEY: ${{ secrets.REACT_APP_API_SUBSCRIPTION_KEY }}
        run: npm test
  
